### PR TITLE
Separate etcpal/lock.h into discrete modules

### PR DESCRIPTION
**Pull request by samkearney**
EtcPal has two new OS synchronization features on the horizon, recursive mutexes and events. We should no longer have one monolithic "lock.h" covering all synchronization primitives, as it will get more and more wrong, and doesn't match the slim-module pattern of the rest of the library. This PR separates lock.h into mutex.h, rwlock.h, sem.h and signal.h.

### CODE REVIEW

**Comment by nwagner** [comment]
Looks fairly straightforward.  I think my only comment is that we might still want to consider a "lock.h" that includes the other platform neutral locks, but I don't feel strongly about it.

**Review by nwagner — APPROVED** [review]

**Review by ChristianReese — APPROVED** [review]

**Comment by samkearney** [comment]
@nwagner what "other" platform neutral locks are you referring to? All the current locking primitives supported by EtcPal are represented in this PR.

**Comment by nwagner** [comment]
I was referring to a generic lock.h that apps could include rather than separately including semaphore.h, mutex.h, etc.  A minor convenience header.  Which is why I didn't feel too strongly about having it.

**Comment by samkearney** [comment]
@nwagner  Yeah, but part of the reason for this reorganization is that a counting semaphore is not really a "lock", nor is a signal. So it's not really an accurate name for a header.

**Pull request merged**
